---
baseurl: https://example.com
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: Example Site
disqusShortname: hugo-theme-stack
googleAnalytics: 
DefaultContentLanguage: en
permalinks:
  post: "/p/:slug/"
  page: "/:slug/"
params:
  mainSections:
  - post
  featuredImageField: image
  rssFullContent: true
  favicon: 
  footer:
    since: 2020
    customText: 
  dateFormat:
    published: Jan 02, 2006
    lastUpdated: Jan 02, 2006 15:04 MST
  sidebar:
    emoji: "\U0001F365"
    subtitle: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    avatar:
      enabled: true
      local: true
      src: img/avatar.png
  article:
    math: false
    toc: true
    readingTime: true
    license:
      enabled: true
      default: Licensed under CC BY-NC-SA 4.0
  comments:
    enabled: true
    provider: disqus
    disqusjs:
      shortname: 
      apiUrl: 
      apiKey: 
      admin: 
      adminLabel: 
    utterances:
      repo: 
      issueTerm: pathname
      label: 
    remark42:
      host: 
      site: 
      locale: 
    vssue:
      platform: 
      owner: 
      repo: 
      clientId: 
      clientSecret: 
      autoCreateIssue: false
    waline:
      serverURL: 
      lang: 
      visitor: 
      avatar: 
      emoji:
      - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
      requiredMeta:
      - name
      - email
      - url
      placeholder: 
      locale:
        admin: Admin
    twikoo:
      envId: 
      region: 
      path: 
      lang: 
    giscus:
      repo: 
      repoID: 
      category: 
      categoryID: 
      mapping: 
      lightTheme: 
      darkTheme: 
      reactionsEnabled: 1
      emitMetadata: 0
    gitalk:
      owner: 
      admin: 
      repo: 
      clientID: 
      clientSecret: 
  widgets:
    enabled:
    - search
    - archives
    - tag-cloud
    archives:
      limit: 5
    tagCloud:
      limit: 10
  opengraph:
    twitter:
      site: 
      card: summary_large_image
  defaultImage:
    opengraph:
      enabled: false
      local: false
      src: 
  colorScheme:
    toggle: true
    default: auto
  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true
menu:
  main:
  - url: "/"
    name: Test
    weight: 5
  - pre: home
    url: "/"
    name: Home
    params:
      newTab: true
    weight: 1
    identifier: home
related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
  - name: tags
    weight: 100
  - name: categories
    weight: 200
markup:
  goldmark:
    renderer:
      unsafe: false
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
